baseURL = 'https://koalaawad.github.io/'
languageCode = 'en-us'
title = 'Awad'
theme = 'terminal'

[params]
  contentTypeName = "posts"
  themeColor = "blue"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = true

[params.logo]
  logoText = "awad.terminal"
  logoHomeLink = "/"

[markup.goldmark.renderer]
  unsafe = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 1
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts"
    weight = 2
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    weight = 3
  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume"
    weight = 4

